### ISSUE TITLE
DRBD/NFS Automated Configuration title in automation docs is not really accurate

### ISSUE THREAD

**Issue by arbulu89** [SUSE/doc-slesforsap#40]
The section title `DRBD/NFS Automated Configuration` in the automation documentation page is not really accurate.

The `drbd-formula` only configures DRBD, not NFS. In order to use NFS, we need to do things on top of it.

The thing is that SUSE recommends to use DRBD with HA to have a high available NFS share. For that, we configure the HA cluster in top of DRBD to create the NFS exports. But this is not anything the `drbd-formula` does.

Maybe the title is confusing.

If we want to document how to have high available NFS with DRBD, we will need to add more things (explain that we need to use `drbd-formula` and `habootstrap-formula`, and after that apply a specific configuration to the cluster to setup as NFS).

**Comment by tomschr** [comment]
@arbulu89 Thanks Xabier and sorry for the delay.

You are right. Currently not sure how to deal with that. I see these solutions:

1. Just correct the title to have "DRBD" in the title and remove the "NFS" word.
2. Extend it with additional information regarding NFS. As you said, we need more things. Is the `habootstrap-formula` just enough for NFS or an overkill? 
3. Add a link/short paragraph in the upstream `drbd-formula` project.

* Solution 1 is probably the easiest to do and done in a second. :wink: 
* For solution 2 I guess I would need a more better understanding.
* Solution 3 would work too. Maybe we could add a short section/paragraph about "Further Ideas/Formulas/...". That section should probably be added to the very end so the user doesn't confuse it as a mandatory step.

Any thoughts?

**Comment by arbulu89** [comment]
Hi @tomschr ,
I'm afraid there is not easy answer for this hehe
Just thinking that we are dealing with SAP users most of the time, we need to consider their knowledge domain. This means (most of the times) that they don't really care if the storage is implemented using DRBD or other platforms. DRBD is just a detail for them. The domain they understand is the `shared storage` concept, and if it's HA or not. That's why, we need to carefully think what is the real purpose of this document.

The `drbd-formula` just deals with DRBD. And it behind that, we have the fact the SUSE recommends to use this technology to create HA NFS share options (what is what the customers look for). So, in essence DRBD is not really market/user oriented.

Sooooo,
If we want to talk SAP/users language, we need to talk about NFS, and say that we achieve this using `drbd-formula` and `habootstrap-formula`. On the contrary, if the document is just technical, we could ignore this fact.

I would be for the 1st option, so we should address the chapter to talk about HA NFS, and explain that we use drbd and HA cluster for that.

What do you think?
This will require some changes on the doc, that's true
